// ── EXPRESIONES ────────────────────────────────────────────────────────────────
const EXPR=[
  // ── PALABRAS BÁSICAS (prio:2 — siempre se traducen primero) ──────────────────
  // Artículos
  {es:'el',en:'the',fr:'le',de:'der',it:'il',pt:'o',ca:'el',prio:3},
  {es:'la',en:'the',fr:'la',de:'die',it:'la',pt:'a',ca:'la',prio:3},
  {es:'los',en:'the',fr:'les',de:'die',it:'i',pt:'os',ca:'els',prio:3},
  {es:'las',en:'the',fr:'les',de:'die',it:'le',pt:'as',ca:'les',prio:3},
  {es:'un',en:'a',fr:'un',de:'ein',it:'un',pt:'um',ca:'un',prio:3},
  {es:'una',en:'a',fr:'une',de:'eine',it:'una',pt:'uma',ca:'una',prio:3},
  {es:'unos',en:'some',fr:'des',de:'einige',it:'alcuni',pt:'uns',ca:'uns',prio:3},
  {es:'unas',en:'some',fr:'des',de:'einige',it:'alcune',pt:'umas',ca:'unes',prio:3},
  // Pronombres personales
  {es:'yo',en:'I',fr:'je',de:'ich',it:'io',pt:'eu',ca:'jo',prio:3},
  {es:'tú',en:'you',fr:'tu',de:'du',it:'tu',pt:'tu',ca:'tu',prio:3},
  {es:'él',en:'he',fr:'il',de:'er',it:'lui',pt:'ele',ca:'ell',prio:3},
  {es:'ella',en:'she',fr:'elle',de:'sie',it:'lei',pt:'ela',ca:'ella',prio:3},
  {es:'nosotros',en:'we',fr:'nous',de:'wir',it:'noi',pt:'nós',ca:'nosaltres',prio:3},
  {es:'ellos',en:'they',fr:'ils',de:'sie',it:'loro',pt:'eles',ca:'ells',prio:3},
  {es:'ellas',en:'they',fr:'elles',de:'sie',it:'loro',pt:'elas',ca:'elles',prio:3},
  // Preposiciones y conectores básicos
  {es:'en',en:'in',fr:'dans',de:'in',it:'in',pt:'em',ca:'en',prio:2},
  {es:'con',en:'with',fr:'avec',de:'mit',it:'con',pt:'com',ca:'amb',prio:2},
  {es:'por',en:'for',fr:'pour',de:'für',it:'per',pt:'por',ca:'per',prio:2},
  {es:'para',en:'for',fr:'pour',de:'für',it:'per',pt:'para',ca:'per',prio:2},
  {es:'que',en:'that',fr:'que',de:'dass',it:'che',pt:'que',ca:'que',prio:2},
  {es:'como',en:'like',fr:'comme',de:'wie',it:'come',pt:'como',ca:'com',prio:2},
  {es:'pero',en:'but',fr:'mais',de:'aber',it:'ma',pt:'mas',ca:'però',prio:2},
  {es:'muy',en:'very',fr:'très',de:'sehr',it:'molto',pt:'muito',ca:'molt',prio:2},
  {es:'más',en:'more',fr:'plus',de:'mehr',it:'più',pt:'mais',ca:'més',prio:2},
  {es:'todo',en:'all',fr:'tout',de:'alles',it:'tutto',pt:'tudo',ca:'tot',prio:2},
  {es:'tan',en:'so',fr:'si',de:'so',it:'così',pt:'tão',ca:'tan',prio:2},
  {es:'cuando',en:'when',fr:'quand',de:'wenn',it:'quando',pt:'quando',ca:'quan',prio:2},
  {es:'donde',en:'where',fr:'où',de:'wo',it:'dove',pt:'onde',ca:'on',prio:2},
  {es:'porque',en:'because',fr:'parce que',de:'weil',it:'perché',pt:'porque',ca:'perquè',prio:2},
  {es:'siempre',en:'always',fr:'toujours',de:'immer',it:'sempre',pt:'sempre',ca:'sempre',prio:2},
  {es:'nunca',en:'never',fr:'jamais',de:'nie',it:'mai',pt:'nunca',ca:'mai',prio:2},
  {es:'ahora',en:'now',fr:'maintenant',de:'jetzt',it:'adesso',pt:'agora',ca:'ara',prio:2},
  {es:'después',en:'after',fr:'après',de:'danach',it:'dopo',pt:'depois',ca:'després',prio:2},
  {es:'antes',en:'before',fr:'avant',de:'vor',it:'prima',pt:'antes',ca:'abans',prio:2},
  {es:'también',en:'also',fr:'aussi',de:'auch',it:'anche',pt:'também',ca:'també',prio:2},
  // Verbos muy comunes
  {es:'era',en:'was',fr:'était',de:'war',it:'era',pt:'era',ca:'era',prio:2},
  {es:'fue',en:'was',fr:'fut',de:'war',it:'fu',pt:'foi',ca:'fou',prio:2},
  {es:'tenía',en:'had',fr:'avait',de:'hatte',it:'aveva',pt:'tinha',ca:'tenia',prio:2},
  {es:'había',en:'there was',fr:'il y avait',de:'es gab',it:"c'era",pt:'havia',ca:'hi havia',prio:2},
  {es:'podía',en:'could',fr:'pouvait',de:'konnte',it:'poteva',pt:'podia',ca:'podia',prio:2},
  {es:'dijo',en:'said',fr:'dit',de:'sagte',it:'disse',pt:'disse',ca:'va dir',prio:2},
  {es:'vio',en:'saw',fr:'vit',de:'sah',it:'vide',pt:'viu',ca:'va veure',prio:2},
  {es:'llegó',en:'arrived',fr:'arriva',de:'kam an',it:'arrivò',pt:'chegou',ca:'va arribar',prio:2},

  {es:'había una vez',en:'once upon a time',fr:'il était une fois',de:'es war einmal',it:"c'era una volta",pt:'era uma vez',ca:'hi havia una vegada',prio:1},
  {es:'y vivieron felices para siempre',en:'and they lived happily ever after',fr:'et ils vécurent heureux pour toujours',de:'und sie lebten glücklich',it:'e vissero felici e contenti',pt:'e viveram felizes para sempre',ca:'i visqueren feliços per sempre',prio:1},
  {es:'de repente',en:'suddenly',fr:'soudain',de:'plötzlich',it:"all'improvviso",pt:'de repente',ca:'de sobte',prio:1},
  {es:'sin embargo',en:'however',fr:'cependant',de:'jedoch',it:'tuttavia',pt:'no entanto',ca:'tanmateix',prio:1},
  {es:'a lo lejos',en:'in the distance',fr:'au loin',de:'in der Ferne',it:'in lontananza',pt:'ao longe',ca:'a la llunyania',prio:1},
  {es:'por fin',en:'at last',fr:'enfin',de:'endlich',it:'finalmente',pt:'por fim',ca:'per fi',prio:1},
  {es:'poco a poco',en:'little by little',fr:'peu à peu',de:'nach und nach',it:'poco a poco',pt:'pouco a pouco',ca:'a poc a poc',prio:1},
  {es:'al cabo de los años',en:'after many years',fr:'après de nombreuses années',de:'nach vielen Jahren',it:'dopo tanti anni',pt:'passados muitos anos',ca:'al cap dels anys',prio:1},
  {es:'al mismo tiempo',en:'at the same time',fr:'en même temps',de:'zur gleichen Zeit',it:'allo stesso tempo',pt:'ao mesmo tempo',ca:'al mateix temps'},
  {es:'en cambio',en:'instead',fr:'en revanche',de:'hingegen',it:'invece',pt:'em vez disso',ca:'en canvi'},
  {es:'rey',en:'king',fr:'roi',de:'König',it:'re',pt:'rei',ca:'rei',prio:1},
  {es:'reina',en:'queen',fr:'reine',de:'Königin',it:'regina',pt:'rainha',ca:'reina',prio:1},
  {es:'príncipe',en:'prince',fr:'prince',de:'Prinz',it:'principe',pt:'príncipe',ca:'príncep',prio:1},
  {es:'princesa',en:'princess',fr:'princesse',de:'Prinzessin',it:'principessa',pt:'princesa',ca:'princesa',prio:1},
  {es:'castillo',en:'castle',fr:'château',de:'Schloss',it:'castello',pt:'castelo',ca:'castell',prio:1},
  {es:'bosque',en:'forest',fr:'forêt',de:'Wald',it:'foresta',pt:'floresta',ca:'bosc',prio:1},
  {es:'bruja',en:'witch',fr:'sorcière',de:'Hexe',it:'strega',pt:'bruxa',ca:'bruixa',prio:1},
  {es:'espejo',en:'mirror',fr:'miroir',de:'Spiegel',it:'specchio',pt:'espelho',ca:'mirall',prio:1},
  {es:'manzana',en:'apple',fr:'pomme',de:'Apfel',it:'mela',pt:'maçã',ca:'poma',prio:1},
  {es:'corazón',en:'heart',fr:'cœur',de:'Herz',it:'cuore',pt:'coração',ca:'cor',prio:1},
  {es:'amor',en:'love',fr:'amour',de:'Liebe',it:'amore',pt:'amor',ca:'amor',prio:1},
  {es:'noche',en:'night',fr:'nuit',de:'Nacht',it:'notte',pt:'noite',ca:'nit',prio:1},
  {es:'luna',en:'moon',fr:'lune',de:'Mond',it:'luna',pt:'lua',ca:'lluna',prio:1},
  {es:'estrellas',en:'stars',fr:'étoiles',de:'Sterne',it:'stelle',pt:'estrelas',ca:'estrelles',prio:1},
  {es:'padre',en:'father',fr:'père',de:'Vater',it:'padre',pt:'pai',ca:'pare',prio:1},
  {es:'madre',en:'mother',fr:'mère',de:'Mutter',it:'madre',pt:'mãe',ca:'mare',prio:1},
  {es:'hermana',en:'sister',fr:'sœur',de:'Schwester',it:'sorella',pt:'irmã',ca:'germana',prio:1},
  {es:'hermano',en:'brother',fr:'frère',de:'Bruder',it:'fratello',pt:'irmão',ca:'germà',prio:1},
  {es:'hija',en:'daughter',fr:'fille',de:'Tochter',it:'figlia',pt:'filha',ca:'filla',prio:1},
  {es:'hijo',en:'son',fr:'fils',de:'Sohn',it:'figlio',pt:'filho',ca:'fill',prio:1},
  {es:'valiente',en:'brave',fr:'courageux',de:'tapfer',it:'coraggioso',pt:'corajoso',ca:'valent',prio:1},
  {es:'hermosa',en:'beautiful',fr:'belle',de:'schön',it:'bella',pt:'bela',ca:'bella',prio:1},
  {es:'feliz',en:'happy',fr:'heureux',de:'glücklich',it:'felice',pt:'feliz',ca:'feliç',prio:1},
  {es:'miedo',en:'fear',fr:'peur',de:'Angst',it:'paura',pt:'medo',ca:'por',prio:1},
  {es:'esperanza',en:'hope',fr:'espoir',de:'Hoffnung',it:'speranza',pt:'esperança',ca:'esperança',prio:1},
  {es:'verdad',en:'truth',fr:'vérité',de:'Wahrheit',it:'verità',pt:'verdade',ca:'veritat',prio:1},
  {es:'camino',en:'path',fr:'chemin',de:'Weg',it:'sentiero',pt:'caminho',ca:'camí',prio:1},
  {es:'mágico',en:'magical',fr:'magique',de:'magisch',it:'magico',pt:'mágico',ca:'màgic',prio:1},
  {es:'oscuro',en:'dark',fr:'sombre',de:'dunkel',it:'oscuro',pt:'escuro',ca:'fosc',prio:1},
  {es:'cazador',en:'hunter',fr:'chasseur',de:'Jäger',it:'cacciatore',pt:'caçador',ca:'caçador',prio:1},
  {es:'nieve',en:'snow',fr:'neige',de:'Schnee',it:'neve',pt:'neve',ca:'neu',prio:1},
  {es:'sangre',en:'blood',fr:'sang',de:'Blut',it:'sangue',pt:'sangue',ca:'sang',prio:1},
];
EXPR.sort((a,b)=>b.es.length-a.es.length);

// ── LIBROS ────────────────────────────────────────────────────────────────────
// Formato de frases: array de objetos {es, en, fr, de, it, pt, ca}
// Cada objeto es una frase. El motor decide si mostrarla en ES o en el idioma objetivo.
// ── CATÁLOGO LIGERO (sin datos de caps) ──────────────────────────────────────
// Los caps se cargan dinámicamente desde JSON al abrir el libro
const LIBROS=[
  {id:1,tit:`Blancanieves`,aut:'Hermanos Grimm',cat:'Grimm',gratis:true,cov:'grimm',emo:'🍎',totalCaps:5,file:'blancanieves.json',caps:[]},
  {id:2,tit:`La Sirenita`,aut:'H.C. Andersen',cat:'Andersen',gratis:true,cov:'andersen',emo:'🌊',totalCaps:4,file:'sirenita.json',caps:[]},
  {id:3,tit:`Caperucita Roja`,aut:'Hermanos Grimm',cat:'Grimm',gratis:true,cov:'grimm',emo:'🐺',totalCaps:3,file:'caperucita.json',caps:[]},
  {id:4,tit:`El Patito Feo`,aut:'H.C. Andersen',cat:'Andersen',gratis:true,cov:'andersen',emo:'🦢',totalCaps:3,file:'patito.json',caps:[]},
]
